
import os
import markdown

def generate_reports(source_dir):
    chapters = [
        "01_executive_summary.md",
        "02_ai_security.md",
        "03_post_quantum.md",
        "04_space_security.md",
        "05_biotech_cognitive.md",
        "06_top_50_jobs.md",
        "07_roadmap_appendices.md"
    ]

    # Initialize content containers
    full_md_text = ""
    
    # Header for Markdown report
    full_md_text += "# Cybersecurity Deep Research Report: Opportunities in New Domains (2025-2035)\n\n"
    full_md_text += "> Generated by Antigravity Agent | February 2026\n\n---\n\n"

    # Read and combine chapters
    for chapter in chapters:
        file_path = os.path.join(source_dir, chapter)
        if os.path.exists(file_path):
            with open(file_path, "r") as f:
                content = f.read()
                full_md_text += content + "\n\n---\n\n"
        else:
            print(f"Warning: Chapter {chapter} not found.")

    # Save Markdown Report
    md_filename = "Cybersecurity_Report_2025_2035.md"
    with open(md_filename, "w") as f:
        f.write(full_md_text)
    print(f"Generated Markdown Report: {md_filename}")

    # Convert to HTML
    html_body = markdown.markdown(full_md_text, extensions=['extra', 'codehilite', 'toc'])
    
    # HTML Template with CSS for print
    html_template = f"""
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Cybersecurity Deep Research Report (2025-2035)</title>
        <style>
            @import url('https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;700&family=Merriweather:wght@300;400;700&display=swap');
            
            body {{
                font-family: 'Merriweather', serif;
                line-height: 1.6;
                color: #333;
                max-width: 800px;
                margin: 0 auto;
                padding: 40px;
                background-color: #f9f9f9;
            }}
            h1, h2, h3, h4 {{
                font-family: 'Roboto', sans-serif;
                color: #2c3e50;
                margin-top: 1.5em;
            }}
            h1 {{
                font-size: 2.5em;
                border-bottom: 2px solid #2c3e50;
                padding-bottom: 10px;
                text-align: center;
                margin-top: 0;
            }}
            h2 {{
                font-size: 1.8em;
                border-bottom: 1px solid #ddd;
                padding-bottom: 5px;
            }}
            h3 {{
                font-size: 1.4em;
                color: #16a085;
            }}
            p {{
                margin-bottom: 1.2em;
                text-align: justify;
            }}
            ul, ol {{
                margin-bottom: 1.2em;
                padding-left: 20px;
            }}
            li {{
                margin-bottom: 5px;
            }}
            blockquote {{
                border-left: 4px solid #16a085;
                padding-left: 15px;
                color: #555;
                font-style: italic;
                background: #fff;
                padding: 10px;
                margin: 20px 0;
            }}
            code {{
                background-color: #eee;
                padding: 2px 4px;
                border-radius: 3px;
                font-family: monospace;
            }}
            hr {{
                border: 0;
                height: 1px;
                background: #ccc;
                margin: 40px 0;
            }}
            .cover {{
                text-align: center;
                margin-bottom: 100px;
            }}
            @media print {{
                body {{
                    background-color: white;
                    max-width: 100%;
                    padding: 0;
                    margin: 2cm;
                }}
                h1 {{
                    page-break-before: always;
                }}
                h1:first-of-type {{
                    page-break-before: auto;
                }}
                a {{
                    text-decoration: none;
                    color: #000;
                }}
            }}
        </style>
    </head>
    <body>
        {html_body}
    </body>
    </html>
    """

    # Save HTML Report
    html_filename = "Cybersecurity_Report_2025_2035.html"
    with open(html_filename, "w") as f:
        f.write(html_template)
    print(f"Generated HTML Report: {html_filename}")

if __name__ == "__main__":
    generate_reports("report_content")
