
import os
import markdown
from xhtml2pdf import pisa

def convert_markdown_to_pdf(source_dir, output_filename):
    # Order of chapters
    chapters = [
        "01_executive_summary.md",
        "02_ai_security.md",
        "03_post_quantum.md",
        "04_space_security.md",
        "05_biotech_cognitive.md",
        "06_top_50_jobs.md",
        "07_roadmap_appendices.md"
    ]

    html_content = """
    <html>
    <head>
    <style>
        @page {
            size: A4;
            margin: 2cm;
            @top-center {
                content: "Opportunities in New Cyber Domains (2025-2035)";
                font-family: Helvetica;
                font-size: 10px;
                color: #555;
            }
            @bottom-center {
                content: counter(page);
                font-family: Helvetica;
                font-size: 10px;
                color: #555;
            }
        }
        body {
            font-family: Helvetica, sans-serif;
            font-size: 12px;
            line-height: 1.5;
            color: #333;
        }
        h1 {
            color: #2c3e50;
            border-bottom: 2px solid #2c3e50;
            padding-bottom: 10px;
            margin-top: 30px;
        }
        h2 {
            color: #34495e;
            margin-top: 25px;
            border-bottom: 1px solid #ddd;
        }
        h3 {
            color: #16a085;
            margin-top: 20px;
        }
        p {
            text-align: justify;
            margin-bottom: 10px;
        }
        li {
            margin-bottom: 5px;
        }
        code {
            background-color: #f4f4f4;
            padding: 2px 4px;
            font-family: monospace;
        }
        .cover-page {
            text-align: center;
            padding-top: 200px;
            page-break-after: always;
        }
        .cover-title {
            font-size: 36px;
            font-weight: bold;
            color: #2c3e50;
            margin-bottom: 20px;
        }
        .cover-subtitle {
            font-size: 24px;
            color: #7f8c8d;
            margin-bottom: 50px;
        }
        .cover-author {
            font-size: 14px;
            color: #95a5a6;
        }
        .toc {
            page-break-after: always;
        }
    </style>
    </head>
    <body>
    <div class="cover-page">
        <div class="cover-title">Cybersecurity Deep Research Report</div>
        <div class="cover-subtitle">Opportunities in New Domains (2025-2035)</div>
        <div class="cover-author">Generated by Antigravity Agent</div>
        <div class="cover-author">Date: February 2026</div>
    </div>
    """

    # Combine markdown content
    full_md_text = ""
    for chapter in chapters:
        file_path = os.path.join(source_dir, chapter)
        if os.path.exists(file_path):
            with open(file_path, "r") as f:
                full_md_text += f.read() + "\n\n"

    # Convert markdown to HTML
    body_html = markdown.markdown(full_md_text, extensions=['extra', 'codehilite'])
    
    html_content += body_html + "</body></html>"

    # Write PDF
    with open(output_filename, "w+b") as result_file:
        pisa_status = pisa.CreatePDF(
            html_content, dest=result_file)

    if pisa_status.err:
        print(f"Error generating PDF: {pisa_status.err}")
    else:
        print(f"PDF successfully generated: {output_filename}")

if __name__ == "__main__":
    convert_markdown_to_pdf("report_content", "Cybersecurity_Report_2025_2035.pdf")
